reviewers:
  # The default reviewers
  defaults:
    - repository-owners # group
    - nate-double-u # username
    - team:default-reviewers # GitHub team

  # Reviewer groups each of which has a list of GitHub usernames
  groups:
    repository-owners:
      - nate-double-u # username
      - hackabletype
      - team:owners # GitHub team
  #  core-contributors:
  #    - nate-double-u # username

  # Reviewers per author.
  # Keys are reviewees, each of which has an array of reviewers.
  #per_author:
  #  engineers:
  #    - engineers # group
  #    - team:engineering-managers # GitHub team
  #  lead_designer:
  #    - js-lovers # group
  #    - desinger_a # username
  #  designer_a:
  #    - lead_designer # username
  #  designer_b:
  #    - lead_desinger # username
  #    - desinger_a # username

files:
  # Keys are glob expressions.
  # You can assign groups defined above as well as GitHub usernames.
  '**':
    - repository-owners # group

options:
  ignore_draft: false
  ignored_keywords:
    - DO NOT REVIEW
  enable_group_assignment: false

  # Randomly pick reviewers up to this number.
  # Do not set this option if you'd like to assign all matching reviewers.
  number_of_reviewers: 3

  # If it's true, the last matching files-change pattern takes the most precedence (CODEOWNERS-compatible)
  # See https://github.com/necojackarc/auto-request-review/pull/80 for more details.
  last_files_match_only: false
